name: env_colombians_migration
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.4
  - numpy=1.26.3
  - matplotlib=3.8.2
  - seaborn=0.13.2
  - sqlalchemy=2.0.23
  - requests=2.31.0
  - ipykernel
  - psycopg2-binary=2.9.9
  - jinja2=3.1.4